### PR TITLE
Add tests for indexing to solr/fuseki

### PR DESCRIPTION
**Pull request by whikloj**
For @awoods 

To handle JSON parsing on the command line I took @Rarian's suggestion. This means you need to install [jq](https://stedolan.github.io/jq/) on your machine to use this. We could provide the binaries, but I think that is probably asking for trouble.

This creates an object in Fedora, and attempts to query it out of Solr and Fuseki.

### CODE REVIEW

**Comment by awoods** [comment]
@whikloj, can you please link the associated JIRA ticket to this? ...and create one if necessary.

**Comment by whikloj** [comment]
@awoods there is [FCREPO-1969](https://jira.duraspace.org/browse/FCREPO-1969) which we never resolved. This does still fit.

Question is, should i make it "Under Review"? And would this work resolve that ticket, or should it remain in progress?

**Comment by awoods** [comment]
@whikloj, I think https://jira.duraspace.org/browse/FCREPO-1969 does the trick... quite reasonably leaving out the HTML/user-interaction piece.

**Comment by awoods** [comment]
@whikloj, I think https://jira.duraspace.org/browse/FCREPO-1969 does the trick... quite reasonably leaving out the HTML/user-interaction piece.

**Comment by awoods** [comment]
@whikloj, I think https://jira.duraspace.org/browse/FCREPO-1969 does the trick... quite reasonably leaving out the HTML/user-interaction piece.

**Comment by whikloj** [comment]
Sounds good, I'd love to do the HTML UI tests but that seems like a long term goal.

**Comment by awoods** [comment]
@whikloj , just testing this PR out... and the test consistently fails for me:

```
Checking for item in Solr....../camel_toolbox_tests.sh: line 34: [: : integer expression expected

ERROR expected http://localhost:8080/fcrepo/rest/test_camel/object_to_index and received 
```

**Pull request merged**
